spring:
  application:
    name: order-flow

  datasource:
    url: jdbc:postgresql://localhost:5432/order_flow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never

  jackson:
    serialization:
      indent-output: true

order:
  payment:
    provider:
      base-url: http://localhost:8081
      api-key: local-dev-key
